# Generated by Django 2.1.3 on 2018-11-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181126_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
